version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: fintrack_postgres
    restart: always
    environment:
      POSTGRES_USER: fintrack
      POSTGRES_PASSWORD: fintrack123
      POSTGRES_DB: fintrack_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
